version: "1"
services:
  - type: web
    name: laburobot
    runtime: ruby
    repo: https://github.com/gonzabt3/laburobot
    plan: free
    region: oregon
    buildCommand: |
      bundle install
      npm install
      SECRET_KEY_BASE_DUMMY=1 bundle exec rake assets:precompile
      bundle exec rake assets:clean
    startCommand: bundle exec rails db:prepare && bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}
    autoDeployTrigger: commit
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"